namespace Refresh.Interfaces.Game.Types.Telemetry;

public static class TelemetryConfig
{
    // Removed because unnecessary:
    // - E_TELEMETRY_EVENT_DLC_PROFILE
    public const string Default = 
        """
        <t_enable>true</t_enable>
        <t_bandwidth_cap>32000.0</t_bandwidth_cap>
        <t_secs_between_flush_buffer>5.0</t_secs_between_flush_buffer>
        <t_version>1</t_version>
        <t_max_dlc_to_report>32</t_max_dlc_to_report>

        <t_percentages>
            <E_TELEMETRY_EVENT_DEBUG_NAME_LOOKUP>100.0</E_TELEMETRY_EVENT_DEBUG_NAME_LOOKUP>
            <E_TELEMETRY_EVENT_MEMORY_STATS>100.0</E_TELEMETRY_EVENT_MEMORY_STATS>
            <E_TELEMETRY_EVENT_BOOT_START>100.0</E_TELEMETRY_EVENT_BOOT_START>
            <E_TELEMETRY_EVENT_PLAYER_PROFILE>100.0</E_TELEMETRY_EVENT_PLAYER_PROFILE>
            <E_TELEMETRY_EVENT_FRIEND_PROFILE>100.0</E_TELEMETRY_EVENT_FRIEND_PROFILE>
            <E_TELEMETRY_EVENT_HARDWARE_PROFILE>100.0</E_TELEMETRY_EVENT_HARDWARE_PROFILE>
            <E_TELEMETRY_EVENT_NETWORK_PROFILE>100.0</E_TELEMETRY_EVENT_NETWORK_PROFILE>
            <E_TELEMETRY_EVENT_GAME_START>100.0</E_TELEMETRY_EVENT_GAME_START>
            <E_TELEMETRY_EVENT_PLAYER_JOIN>100.0</E_TELEMETRY_EVENT_PLAYER_JOIN>
            <E_TELEMETRY_EVENT_PLAYER_LEAVE>100.0</E_TELEMETRY_EVENT_PLAYER_LEAVE>
            <E_TELEMETRY_EVENT_GAME_END>100.0</E_TELEMETRY_EVENT_GAME_END>
            <E_TELEMETRY_EVENT_PLAYER_SCORE>100.0</E_TELEMETRY_EVENT_PLAYER_SCORE>
            <E_TELEMETRY_EVENT_STORE_START>100.0</E_TELEMETRY_EVENT_STORE_START>
            <E_TELEMETRY_EVENT_STORE_MENU_SCREEN>100.0</E_TELEMETRY_EVENT_STORE_MENU_SCREEN>
            <E_TELEMETRY_EVENT_ITEM_DETAIL_VIEW>100.0</E_TELEMETRY_EVENT_ITEM_DETAIL_VIEW>
            <E_TELEMETRY_EVENT_ITEM_ADDED_TO_CART>100.0</E_TELEMETRY_EVENT_ITEM_ADDED_TO_CART>
            <E_TELEMETRY_EVENT_ITEM_REMOVE_FROM_CART>100.0</E_TELEMETRY_EVENT_ITEM_REMOVE_FROM_CART>
            <E_TELEMETRY_EVENT_CART_CHECKOUT_PROCESS_STARTED>100.0</E_TELEMETRY_EVENT_CART_CHECKOUT_PROCESS_STARTED>
            <E_TELEMETRY_EVENT_CART_RESULT_DATA>100.0</E_TELEMETRY_EVENT_CART_RESULT_DATA>
            <E_TELEMETRY_EVENT_STORE_END>100.0</E_TELEMETRY_EVENT_STORE_END>
            <E_TELEMETRY_EVENT_ERROR>100.0</E_TELEMETRY_EVENT_ERROR>
            <E_TELEMETRY_EVENT_TROPHY_ACHIEVE>100.0</E_TELEMETRY_EVENT_TROPHY_ACHIEVE>
            <E_TELEMETRY_EVENT_SOCIAL_INTERACTION>100.0</E_TELEMETRY_EVENT_SOCIAL_INTERACTION>
            <E_TELEMETRY_EVENT_MENU_SCREEN>100.0</E_TELEMETRY_EVENT_MENU_SCREEN>
            <E_TELEMETRY_EVENT_LEVEL_PUBLISH>100.0</E_TELEMETRY_EVENT_LEVEL_PUBLISH>
            <E_TELEMETRY_EVENT_INVENTORY_ITEM_CLICK>100.0</E_TELEMETRY_EVENT_INVENTORY_ITEM_CLICK>
            <E_TELEMETRY_EVENT_MODAL_OVERLAY_STATE>100.0</E_TELEMETRY_EVENT_MODAL_OVERLAY_STATE>
            <E_TELEMETRY_EVENT_TAKE_PHOTO>100.0</E_TELEMETRY_EVENT_TAKE_PHOTO>
            <E_TELEMETRY_EVENT_ITEM_HEARTED>100.0</E_TELEMETRY_EVENT_ITEM_HEARTED>
            <E_TELEMETRY_EVENT_DEATH_POSITION>100.0</E_TELEMETRY_EVENT_DEATH_POSITION>
            <E_TELEMETRY_EVENT_SUICIDE_POSITION>100.0</E_TELEMETRY_EVENT_SUICIDE_POSITION>
            <E_TELEMETRY_EVENT_RESTART_POSITION>100.0</E_TELEMETRY_EVENT_RESTART_POSITION>
            <E_TELEMETRY_EVENT_LOST_ALL_LIVES_POSITION>100.0</E_TELEMETRY_EVENT_LOST_ALL_LIVES_POSITION>
            <E_TELEMETRY_EVENT_QUIT_POSITION>100.0</E_TELEMETRY_EVENT_QUIT_POSITION>
            <E_TELEMETRY_EVENT_CONNECTION_QUALITY>100.0</E_TELEMETRY_EVENT_CONNECTION_QUALITY>
            <E_TELEMETRY_EVENT_USER_EXPERIENCE_METRICS>100.0</E_TELEMETRY_EVENT_USER_EXPERIENCE_METRICS>
            <E_TELEMETRY_EVENT_LIVE_STREAM_STARTED>100.0</E_TELEMETRY_EVENT_LIVE_STREAM_STARTED>
            <E_TELEMETRY_EVENT_LIVE_STREAM_UPDATE>100.0</E_TELEMETRY_EVENT_LIVE_STREAM_UPDATE>
            <E_TELEMETRY_EVENT_LIVE_STREAM_ENDED>100.0</E_TELEMETRY_EVENT_LIVE_STREAM_ENDED>
            <E_TELEMETRY_EVENT_PLAY_NOW>100.0</E_TELEMETRY_EVENT_PLAY_NOW>
            <E_TELEMETRY_EVENT_QUEST_ADDED>100.0</E_TELEMETRY_EVENT_QUEST_ADDED>
            <E_TELEMETRY_EVENT_QUEST_COMPLETED>100.0</E_TELEMETRY_EVENT_QUEST_COMPLETED>
            <E_TELEMETRY_EVENT_OBJECTIVE_COMPLETED>100.0</E_TELEMETRY_EVENT_OBJECTIVE_COMPLETED>
            <E_TELEMETRY_EVENT_COMMUNITY_ACTION_UI>100.0</E_TELEMETRY_EVENT_COMMUNITY_ACTION_UI>
            <E_TELEMETRY_EVENT_TUTORIAL_VIDEO>100.0</E_TELEMETRY_EVENT_TUTORIAL_VIDEO>
            <E_TELEMETRY_EVENT_STORE_TEXT_SEARCH>100.0</E_TELEMETRY_EVENT_STORE_TEXT_SEARCH>
            <E_TELEMETRY_EVENT_COMMUNITY_TEXT_SEARCH>100.0</E_TELEMETRY_EVENT_COMMUNITY_TEXT_SEARCH>
            <E_TELEMETRY_EVENT_PIN_ACHIEVE>100.0</E_TELEMETRY_EVENT_PIN_ACHIEVE>
            <E_TELEMETRY_EVENT_PIN_ACHIEVE_FIRST_TIME>100.0</E_TELEMETRY_EVENT_PIN_ACHIEVE_FIRST_TIME>
            <E_TELEMETRY_EVENT_IMPORT_PHOTO>100.0</E_TELEMETRY_EVENT_IMPORT_PHOTO>
            <E_TELEMETRY_CHECKPOINT_RESPAWNED>100.0</E_TELEMETRY_CHECKPOINT_RESPAWNED>
            <E_TELEMETRY_CHECKPOINT_HIT>100.0</E_TELEMETRY_CHECKPOINT_HIT>
            <E_TELEMETRY_CREATURE_TRACK>100.0</E_TELEMETRY_CREATURE_TRACK>
            <E_TELEMETRY_MISSING_RESOURCE>100.0</E_TELEMETRY_MISSING_RESOURCE>
            <E_TELEMETRY_MISSING_NETWORK_RESOURCE>100.0</E_TELEMETRY_MISSING_NETWORK_RESOURCE>
            <E_TELEMETRY_TRYING_TO_PUBLISH_DLC>100.0</E_TELEMETRY_TRYING_TO_PUBLISH_DLC>
            <E_TELEMETRY_NETWORK_JOIN_RESULT>100.0</E_TELEMETRY_NETWORK_JOIN_RESULT>
            <E_TELEMETRY_NETWORK_ERROR>100.0</E_TELEMETRY_NETWORK_ERROR>
            <E_TELEMETRY_ANIMATION_SELECTED>100.0</E_TELEMETRY_ANIMATION_SELECTED>
            <E_TELEMETRY_SOUND_SELECTED>100.0</E_TELEMETRY_SOUND_SELECTED>
            <E_TELEMETRY_HACKED_LEVEL>100.0</E_TELEMETRY_HACKED_LEVEL>
            <E_TELEMETRY_DIVE_IN_EVENT>100.0</E_TELEMETRY_DIVE_IN_EVENT>
            <E_TELEMETRY_GENERIC_MESSAGE>100.0</E_TELEMETRY_GENERIC_MESSAGE>
            <E_TELEMETRY_EVENT_COUNT>100.0</E_TELEMETRY_EVENT_COUNT>
            <E_TELEMETRY_EVENT_INVALID>100.0</E_TELEMETRY_EVENT_INVALID>
            
        </t_percentages>

        <t_timing>
            <E_TELEMETRY_EVENT_DEBUG_NAME_LOOKUP>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_DEBUG_NAME_LOOKUP>
            <E_TELEMETRY_EVENT_MEMORY_STATS>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_MEMORY_STATS>
            <E_TELEMETRY_EVENT_BOOT_START>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_BOOT_START>
            <E_TELEMETRY_EVENT_PLAYER_PROFILE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PLAYER_PROFILE>
            <E_TELEMETRY_EVENT_FRIEND_PROFILE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_FRIEND_PROFILE>
            <E_TELEMETRY_EVENT_HARDWARE_PROFILE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_HARDWARE_PROFILE>
            <E_TELEMETRY_EVENT_NETWORK_PROFILE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_NETWORK_PROFILE>
            <E_TELEMETRY_EVENT_GAME_START>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_GAME_START>
            <E_TELEMETRY_EVENT_PLAYER_JOIN>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PLAYER_JOIN>
            <E_TELEMETRY_EVENT_PLAYER_LEAVE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PLAYER_LEAVE>
            <E_TELEMETRY_EVENT_GAME_END>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_GAME_END>
            <E_TELEMETRY_EVENT_PLAYER_SCORE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PLAYER_SCORE>
            <E_TELEMETRY_EVENT_STORE_START>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_STORE_START>
            <E_TELEMETRY_EVENT_STORE_MENU_SCREEN>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_STORE_MENU_SCREEN>
            <E_TELEMETRY_EVENT_ITEM_DETAIL_VIEW>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_ITEM_DETAIL_VIEW>
            <E_TELEMETRY_EVENT_ITEM_ADDED_TO_CART>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_ITEM_ADDED_TO_CART>
            <E_TELEMETRY_EVENT_ITEM_REMOVE_FROM_CART>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_ITEM_REMOVE_FROM_CART>
            <E_TELEMETRY_EVENT_CART_CHECKOUT_PROCESS_STARTED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_CART_CHECKOUT_PROCESS_STARTED>
            <E_TELEMETRY_EVENT_CART_RESULT_DATA>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_CART_RESULT_DATA>
            <E_TELEMETRY_EVENT_STORE_END>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_STORE_END>
            <E_TELEMETRY_EVENT_ERROR>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_ERROR>
            <E_TELEMETRY_EVENT_TROPHY_ACHIEVE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_TROPHY_ACHIEVE>
            <E_TELEMETRY_EVENT_SOCIAL_INTERACTION>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_SOCIAL_INTERACTION>
            <E_TELEMETRY_EVENT_MENU_SCREEN>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_MENU_SCREEN>
            <E_TELEMETRY_EVENT_LEVEL_PUBLISH>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_LEVEL_PUBLISH>
            <E_TELEMETRY_EVENT_INVENTORY_ITEM_CLICK>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_INVENTORY_ITEM_CLICK>
            <E_TELEMETRY_EVENT_MODAL_OVERLAY_STATE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_MODAL_OVERLAY_STATE>
            <E_TELEMETRY_EVENT_TAKE_PHOTO>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_TAKE_PHOTO>
            <E_TELEMETRY_EVENT_ITEM_HEARTED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_ITEM_HEARTED>
            <E_TELEMETRY_EVENT_DEATH_POSITION>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_DEATH_POSITION>
            <E_TELEMETRY_EVENT_SUICIDE_POSITION>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_SUICIDE_POSITION>
            <E_TELEMETRY_EVENT_RESTART_POSITION>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_RESTART_POSITION>
            <E_TELEMETRY_EVENT_LOST_ALL_LIVES_POSITION>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_LOST_ALL_LIVES_POSITION>
            <E_TELEMETRY_EVENT_QUIT_POSITION>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_QUIT_POSITION>
            <E_TELEMETRY_EVENT_CONNECTION_QUALITY>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_CONNECTION_QUALITY>
            <E_TELEMETRY_EVENT_USER_EXPERIENCE_METRICS>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_USER_EXPERIENCE_METRICS>
            <E_TELEMETRY_EVENT_LIVE_STREAM_STARTED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_LIVE_STREAM_STARTED>
            <E_TELEMETRY_EVENT_LIVE_STREAM_UPDATE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_LIVE_STREAM_UPDATE>
            <E_TELEMETRY_EVENT_LIVE_STREAM_ENDED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_LIVE_STREAM_ENDED>
            <E_TELEMETRY_EVENT_PLAY_NOW>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PLAY_NOW>
            <E_TELEMETRY_EVENT_QUEST_ADDED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_QUEST_ADDED>
            <E_TELEMETRY_EVENT_QUEST_COMPLETED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_QUEST_COMPLETED>
            <E_TELEMETRY_EVENT_OBJECTIVE_COMPLETED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_OBJECTIVE_COMPLETED>
            <E_TELEMETRY_EVENT_COMMUNITY_ACTION_UI>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_COMMUNITY_ACTION_UI>
            <E_TELEMETRY_EVENT_TUTORIAL_VIDEO>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_TUTORIAL_VIDEO>
            <E_TELEMETRY_EVENT_STORE_TEXT_SEARCH>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_STORE_TEXT_SEARCH>
            <E_TELEMETRY_EVENT_COMMUNITY_TEXT_SEARCH>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_COMMUNITY_TEXT_SEARCH>
            <E_TELEMETRY_EVENT_PIN_ACHIEVE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PIN_ACHIEVE>
            <E_TELEMETRY_EVENT_PIN_ACHIEVE_FIRST_TIME>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_PIN_ACHIEVE_FIRST_TIME>
            <E_TELEMETRY_EVENT_IMPORT_PHOTO>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_IMPORT_PHOTO>
            <E_TELEMETRY_CHECKPOINT_RESPAWNED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_CHECKPOINT_RESPAWNED>
            <E_TELEMETRY_CHECKPOINT_HIT>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_CHECKPOINT_HIT>
            <E_TELEMETRY_CREATURE_TRACK>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_CREATURE_TRACK>
            <E_TELEMETRY_MISSING_RESOURCE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_MISSING_RESOURCE>
            <E_TELEMETRY_MISSING_NETWORK_RESOURCE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_MISSING_NETWORK_RESOURCE>
            <E_TELEMETRY_TRYING_TO_PUBLISH_DLC>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_TRYING_TO_PUBLISH_DLC>
            <E_TELEMETRY_NETWORK_JOIN_RESULT>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_NETWORK_JOIN_RESULT>
            <E_TELEMETRY_NETWORK_ERROR>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_NETWORK_ERROR>
            <E_TELEMETRY_ANIMATION_SELECTED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_ANIMATION_SELECTED>
            <E_TELEMETRY_SOUND_SELECTED>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_SOUND_SELECTED>
            <E_TELEMETRY_HACKED_LEVEL>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_HACKED_LEVEL>
            <E_TELEMETRY_DIVE_IN_EVENT>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_DIVE_IN_EVENT>
            <E_TELEMETRY_GENERIC_MESSAGE>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_GENERIC_MESSAGE>
            <E_TELEMETRY_EVENT_COUNT>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_COUNT>
            <E_TELEMETRY_EVENT_INVALID>
                <initial_gap>0.0</initial_gap>
                <subsequent_gap>0.0</subsequent_gap>
            </E_TELEMETRY_EVENT_INVALID>
        </t_timing>

        <t_heatmaps>
            <DISTANCE_BETWEEN_HEATMAP_UPDATES>
            <min>0.0</min>
            <max>100.0</max>
            </DISTANCE_BETWEEN_HEATMAP_UPDATES>
        </t_heatmaps>

        """;
}